### ISSUE TITLE
Cannot use credential passthrough on databricks

### ISSUE THREAD

**Issue by stephlocke** [sparklyr/sparklyr#2342]
When working with Databricks 6.4 (includes Apache Spark 2.4.5, Scala 2.11) on Azure, I'm attempting to use the credential passthrough mechanism to securely connect to Azure Data Lake Storage Gen 2.

I have a prior mounted datalake, that works with SparkR
```r
taxi1 <- SparkR::read.df("/mnt/taxi/yellow/month=0.parquet")
taxi1
```

However, the sparklyr equivalent errors. (Full error at bottom of issue)
>Error : com.databricks.backend.daemon.data.client.adl.AzureCredentialNotFoundException: Could not find ADLS Gen2 Token
```r
sc <- sparklyr::spark_connect(method = "databricks")
taxi1 <- sparklyr::spark_read_parquet("/mnt/taxi/yellow/month=0.parquet", sc=sc)
taxi1
```

Based on some of the config needed for preparing the file mount, I tried adding some extra config but this did not help.
```r
library(sparklyr)
conf <- spark_config()
conf$fs.azure.account.auth.type <- "CustomAccessToken"
conf$fs.azure.account.custom.token.provider.class <- 'com.databricks.backend.daemon.data.client.adl.AdlGen2CredentialContextTokenProvider'
sc <- spark_connect(method = "databricks", config=conf)
```

**Microsoft have a [suggested workaround](https://docs.microsoft.com/en-us/azure/databricks/kb/data-sources/access-adls1-from-sparklyr) however it'd be great to have this fixed.**

I haven't made this fully reproducible but I can provide access to a demo environment when this is being worked on or investigated.

---

> Error : com.databricks.backend.daemon.data.client.adl.AzureCredentialNotFoundException: Could not find ADLS Gen2 Token
> 	at com.databricks.backend.daemon.data.client.adl.AdlGen2CredentialContextTokenProvider$$anonfun$getToken$1.apply(AdlGen2CredentialContextTokenProvider.scala:15)
> 	at com.databricks.backend.daemon.data.client.adl.AdlGen2CredentialContextTokenProvider$$anonfun$getToken$1.apply(AdlGen2CredentialContextTokenProvider.scala:15)
> 	at scala.Option.getOrElse(Option.scala:121)
> 	at com.databricks.backend.daemon.data.client.adl.AdlGen2CredentialContextTokenProvider.getToken(AdlGen2CredentialContextTokenProvider.scala:15)
> 	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.services.AbfsClient.getAccessToken(AbfsClient.java:546)
> 	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.executeHttpOperation(AbfsRestOperation.java:150)
> 	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.execute(AbfsRestOperation.java:124)
> 	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.services.AbfsClient.getAclStatus(AbfsClient.java:498)
> 	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.getIsNamespaceEnabled(AzureBlobFileSystemStore.java:182)
> 	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.getFileStatus(AzureBlobFileSystemStore.java:463)
> 	at shaded.databricks.v20180920_b33d810.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.getFileStatus(AzureBlobFileSystem.java:405)
> 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2$$anonfun$getFileStatus$1$$anonfun$apply$15.apply(DatabricksFileSystemV2.scala:783)
> 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2$$anonfun$getFileStatus$1$$anonfun$apply$15.apply(DatabricksFileSystemV2.scala:780)
> 	at com.databricks.s3a.S3AExeceptionUtils$.convertAWSExceptionToJavaIOException(DatabricksStreamUtils.scala:119)
> 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2$$anonfun$getFileStatus$1.apply(DatabricksFileSystemV2.scala:780)
> 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2$$anonfun$getFileStatus$1.apply(DatabricksFileSystemV2.scala:780)
> 	at com.databricks.logging.UsageLogging$$anonfun$recordOperation$1.apply(UsageLogging.scala:428)
> 	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:238)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
> 	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:233)
> 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionContext(DatabricksFileSystemV2.scala:474)
> 	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:275)
> 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionTags(DatabricksFileSystemV2.scala:474)
> 	at com.databricks.logging.UsageLogging$class.recordOperation(UsageLogging.scala:409)
> 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperation(DatabricksFileSystemV2.scala:474)
> 	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.getFileStatus(DatabricksFileSystemV2.scala:779)
> 	at com.databricks.backend.daemon.data.client.DatabricksFileSystem.getFileStatus(DatabricksFileSystem.scala:197)
> 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1426)
> 	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:613)
> 	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:597)
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
> 	at scala.collection.immutable.List.foreach(List.scala:392)
> 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
> 	at scala.collection.immutable.List.flatMap(List.scala:355)
> 	at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:597)
> 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:391)
> 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:311)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:297)
> 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:748)
> 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:747)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at sparklyr.Invoke.invoke(invoke.scala:147)
> 	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
> 	at sparklyr.StreamHandler.read(stream.scala:66)
> 	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
> 	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by yl790** [comment]
@stephlocke Hey apologies for late reply.

So I created a PR in https://github.com/sparklyr/sparklyr/pull/2368 that might just fix this issue. Not sure what's the easiest way to test such change on my end though.

If it's easier for you to test it, you can tryinstalling my fork of sparklyr with the following

```
library(sparklyr)
devtools::install_github("yl790/sparklyr")
```

and re-run your query through a databrick connection.

**Comment by manikant-prasad** [comment]
@yl790 - Is this issue still open or is there a tentative fix I can try?

**Comment by yl790** [comment]
@manikant-prasad I already pushed all changes that I believe are required in sparklyr for this to work, meanwhile I learned there may be some other changes required from Databricks as well. I'm not sure about the status of the latter set of changes yet.

**Comment by LarsOevlisen** [comment]
@yitao-li, @falaki thank you for your continued work. Do you know the status of getting a fix for this? I tried referencing this at [Databricks](https://forums.databricks.com/questions/47110/cannot-use-credential-passthrough-on-databricks-wh.html), but haven't heard anything yet.

**Comment by yitao-li** [comment]
@LarsOevlisen I'm not entirely sure about how this works end-to-end with Databricks either to be honest.
I made all sparklyr changes I could think of that should get any possible hurdle on sparklyr side out of the way, but there may or may not be things I'm still missing. I'll be more than happy to look into this a bit more with some help or just some hints from Databricks folks as well.

**Comment by nskaff** [comment]
Thank you to everyone who has been working on this issue! Has there been any further movement in the past year? This really is a deal breaker for those of us trying to use sparklyr on Databricks.

**Comment by falaki** [comment]
Hi, we are considering completing this feature in the coming quarter. Please stay tuned.
