### ISSUE TITLE
error to start spark_connect_gateway

### ISSUE THREAD

**Issue by vbucard** [sparklyr/sparklyr#2609]
When I try to execute this command sc<-spark_connect(master = "local", config = config), 

I found this message of error:
Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  : 
  Gateway in localhost:8880 did not respond.

I´m using java jre1.8.0_261 , spark spark-3.0.0-bin-hadoop2.7 , R version 4.0.2 and rstudio 1.3.1056.

How can I fix it?

regards,

Vinicius.

**Comment by yl790** [comment]
@vbucard mind posting the full error message from `spark_connect`? Usually the error message will include the following:

Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (...): Gateway in port (8880) did not respond.
    Path: ...
    Parameters: --class, sparklyr.Backend, ...

---- Output Log ----
...
---- Error Log ----

**Comment by vbucard** [comment]
It is the point.

The message of error shows only this sentence:

Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId, :
Gateway in localhost:8880 did not respond.

Is it possible to set more log of error?

**Comment by vbucard** [comment]
I found the full log of error:

Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId, : Gateway in localhost:8880 did not respond.
6.
stop("Gateway in ", gatewayAddress, ":", gatewayPort, " did not respond.")
5.
spark_connect_gateway(gatewayAddress, gatewayPort, sessionId, config = config, isStarting = TRUE)
4.
withCallingHandlers({ gatewayInfo <- spark_connect_gateway(gatewayAddress, gatewayPort, sessionId, config = config, isStarting = TRUE) break ...
3.
start_shell(master = master, spark_home = spark_home, spark_version = version, app_name = app_name, config = config, jars = spark_config_value(config, c("sparklyr.connect.jars", "sparklyr.jars.default"), list()), packages = spark_config_value(config, c("sparklyr.connect.packages", ...
2.
shell_connection(master = master, spark_home = spark_home, method = method, app_name = app_name, version = version, hadoop_version = hadoop_version, shell_args = shell_args, config = config, service = spark_config_value(config, "sparklyr.gateway.service", FALSE), remote = spark_config_value(config, ...
1.
spark_connect(master = "local")

**Comment by yl790** [comment]
@vbucard Could you try running `options(sparklyr.log.console = TRUE)` before `spark_connect(master = "local")`?

Here's an example of that in action: let's say if the loopback interface is down before I tried running `spark_connect(master = "local")`:

```
ifconfig lo down

R
> library(sparklyr)
> options(sparklyr.log.console = TRUE)
> sc <- spark_connect(master = "local")
```

then there would be some error messages printed out on console indicating what the problem was, e.g.,:

```
* Using Spark: 3.0.0
20/07/22 15:30:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
20/07/22 15:30:08 INFO sparklyr: Session (29629) is starting under 127.0.0.1 port 8880
20/07/22 15:30:08 INFO sparklyr: Session (29629) found port 8880 is available
20/07/22 15:30:08 INFO sparklyr: Gateway (29629) is waiting for sparklyr client to connect to port 8880
20/07/22 15:30:08 ERROR sparklyr: Gateway (29629) Network interface of gateway server socket (lo) is not up.

'ifconfig lo up' (or 'netsh interface set interface name=lo admin=enabled' or similar in Windows) must be run to bring up this network interface.
log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  :
  Gateway in localhost:8880 did not respond.

```

**Comment by vbucard** [comment]
I executed this command options(sparklyr.log.console = TRUE) but r console
didn´t show more log error.

It is showing error like this:

Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  :
  Gateway in localhost:8880 did not respond.

what is the next step?

regards,

Vinicius.

Em qua., 22 de jul. de 2020 às 12:34, Yitao Li <notifications@github.com>
escreveu:

**Comment by yl790** [comment]
@vbucard Wow... Not having any console log from `spark_connect(...)` seems unusual, but not unheard of.

Are you trying to get Apache Spark to work on Windows? If so, did you install winutils as suggested by https://medium.com/big-data-engineering/how-to-install-apache-spark-2-x-in-your-pc-e2047246ffc3? I think the key take-away from that post is there are some additional hurdles one has to overcome in order to make Apache Spark work on Windows unfortunately.

Let me know how else I can help.

**Comment by yl790** [comment]
BTW there is also another post in https://dzone.com/articles/working-on-apache-spark-on-windows that also talks about how to build a trivial Spark application and then submitting it using spark-submit. It may be worthwhile to do this on your current OS just to sanity-check whether your Spark installation is working. Sparklyr currently uses the same spark-submit binary to launch itself so spark-submit must be functional in order for sparklyr to work.

**Comment by vbucard** [comment]
Hi everyone,

i did as you said but when I try to execute spark shell, I received this
message of error

C:\Program Files (x86)\Java>spark-shell
\Java\jre1.8.0_261\bin\java was unexpected at this time.

How can I fix It?

regards,

Vinicius Buçard.

Em qui., 23 de jul. de 2020 às 09:45, Yitao Li <notifications@github.com>
escreveu:

**Comment by yl790** [comment]
@vbucard I believe the error message essentially means you need to surround a path with quotes if the path contains space character. Google is your best friend for OS-specific issues such as whitespace in paths or environmental variables on Windows.

**Comment by Kvit** [comment]
My problem was that Spark could not find Java Runtime Environment (JRE) , I fixed it by:

**Comment by datapoesy** [comment]
Hi all,
I am facing the same error: 
Set up a working cluster in ubuntu. While trying to connect from RStudio to the cluster master.
R version - 4.2.2
Spark - 3.3.1

Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  : 
  Gateway in localhost:8880 did not respond.
I tried disabling the firewall, still the same issue.  Do you have any experience/resolution to share, please?
