### ISSUE TITLE
Databricks Connect and Spark Connect

### ISSUE THREAD

**Issue by nviets** [sparklyr/sparklyr#3443]
# Reporting an Issue with sparklyr

Is sparklyr's databrick_connect method compatible with the opensource Spark Connect feature? I understand from documentation ([here](https://spark.posit.co/deployment/databricks-connect.html#intro) and [here](https://www.databricks.com/blog/2023/04/18/use-databricks-anywhere-databricks-connect-v2.html)] that Databricks Connect is a wrapper around Spark Connect. The examples for sparklyr only demonstrate the vendored method:

```r
sc <- spark_connect(
  cluster_id = "Enter here your cluster ID",
  method = "databricks_connect"
)
```

**Comment by edgararuiz** [comment]
Hi, yes, in fact `pysparklyr` has functions that allow you to start and stop a local instance of Spark Connect, here is the sample code: 

```r
install.packages(pysparklyr)
pysparklyr::install_pyspark("3.5") #Install Spark 3.5 locally so you can run Spark Connect
sparklyr::spark_install("3.5") # Creates a Python environment with the necessary components

library(sparklyr)
pysparklyr::spark_connect_service_start("3.5")
sc <- spark_connect("sc://localhost/" "spark_connect")

# Interact with Spark Connect

spark_disconnect(sc)
pysparklyr::spark_connect_service_stop()
```

**Comment by edgararuiz** [comment]
Hi, I just published a "getting started" article for Spark Connect, here is the link: https://spark.posit.co/deployment/spark-connect.html

**Comment by nviets** [comment]
Thanks, @edgararuiz! Your reply and documentation are really helpful because I wasn't aware of the pysparklyr package. Looking forward to giving this method a try.

**Comment by elango-v** [comment]
Thanks @edgararuiz ! We have been utilizing a Spark standalone cluster via Sparklyr. I am attempting to connect to the same Spark cluster using the approach that you previously mentioned for spark-connect.

However, I am experiencing a few issues when I try to run the spark-connect command. I would appreciate any guidance on how to address these issues.

Existing Spark stand alone cluster connection: (Working) 
----------------------------------------------------------
Sys.setenv(SPARK_CONF_DIR = "/my/custom/spark/conf/path")
Sys.setenv(JAVA_HOME = "/opt/java/jdk8")
Sys.setenv(SPARK_HOME = "/my/custom/spark/home/path")
#assign conf values
sc <- spark_connect(master="spark://mySparkClusterHost:7077", config = conf)

spark-connect connection issue:
--------------------------------
Sys.setenv(SPARK_CONF_DIR = "/my/custom/spark/conf/path")
Sys.setenv(JAVA_HOME = "/opt/java/jdk8")
Sys.setenv(SPARK_HOME = "/my/custom/spark/home/path")
spark_connect_service_start("3.5")
sc <- spark_connect(master = "sc://mySparkClusterHost",method = "spark_connect",version = "3.5.1" )

Error-1 in spark_connect_service_start("3.5"):
----------------------------------------------
Error in `process_initialize(self, private, command, args, stdin, stdout, …`:
! Native call to `processx_exec` failed
Caused by error in `chain_call(c_processx_exec, command, c(command, args), pty, pty_options, …`:
! cannot start processx process '/home/cd-evaithi/spark/spark-3.5-bin-hadoop2.7/sbin/start-connect-server.sh' (system error 2, No such file or directory) @unix/processx.c:611 (processx_exec)
Type .Last.error to see the more details.

We noticed that the `start-connect-server.sh` script was invoked from the standard/default path, which does not exist in our environment.  Supplemented Spark config path was not considered. However, we were able to successfully start the Spark Connect from the CLI by using the following command:
/my/custom/spark/sbin/start-connect-server.sh --packages org.apache.spark:spark-connect_2.12:3.5.1

Error-2 in spark_connect(master = "sc://mySparkClusterHost",method = "spark_connect",version = "3.5.1" ) 
-----------------------------------------------------------------------------------------------------------

! No viable Python Environment was identified for Spark Connect version 3.5.1
  Do you wish to install Spark Connect version 3.5.1?

1: Yes
2: No
3: Cancel

Selection:

Can you please check once?

**Comment by edgararuiz** [comment]
Ok, so a couple of things:

- If you're connecting to an external server, then you don't need to run `spark_connect_service_start()`. That is only needed when you're basically playing with a local Spark service
- You an go ahead and run `pysparklyr::install_pyspark("3.5", python_version = "3.10")` before trying to connect, that way you won't be prompted to install
- Lastly, are we 100% that the `mySparkClusterHost` has the Spark Connect service running?

**Comment by elango-v** [comment]
Thanks @edgararuiz . I installed pysparklyr package now. The reticulate python is set correctly to my custom python environment. Below is my python and R environment details. However when I run the spark_connect statement, I am still getting notification to install Spark connect. Am I missing anything? Can you please check once? Please see below the full code and results from Posit workbench console

Python -3.9, R- 4.3.1, pyspark 3.5.0. Other packages version are listed below.


> Sys.setenv(RETICULATE_PYTHON = "/my/custom/python/bin/python3.9")
> Sys.setenv(SPARK_CONF_DIR = "/my/custom/sparkspark/conf/")
> Sys.setenv(JAVA_HOME = "/opt/java/jdk8")
> Sys.setenv(SPARK_HOME = "/my/custom/python/lib/python3.9/site-packages/pyspark")
> library(dplyr)
> library(reticulate)
> library(sparklyr)
> library(pysparklyr)
> 
> packageVersion("dplyr")
[1] ‘1.1.4’
> packageVersion("reticulate")
[1] ‘1.34.0’
> packageVersion("sparklyr")
[1] ‘1.8.4’
> packageVersion("pysparklyr")
[1] ‘0.1.2’
> 
> use_python("/my/custom/python/bin/python3.9", required=TRUE)
> Sys.getenv("RETICULATE_PYTHON")
[1] "/my/custom/python/bin/python3.9"
> pandas <- import("pandas")
> pyspark <- import ("pyspark")
> numpy <- import("numpy")
> main <- import_main()
> builtins <- import_builtins()
> builtins$print('foo')
foo
> cat("pandas version",pandas$`__version__`)
pandas version 2.0.3> cat("pyspark version",pyspark$`__version__`)
pyspark version 3.5.0> cat("numpy version",numpy$`__version__`)
numpy version 1.25.1> 
> 
> 
> conf <- spark_config()
> conf$`sparklyr.shell.driver-memory` <- "40G"
> conf$spark.executor.memory <- "50GB"
> conf$spark.executor.cores <- 8
> conf$spark.local.dir <- "/shared/hpc/tmp/"
> conf$spark.cores.max <- 32
> conf$sparklyr.connect.enablehivesupport <- FALSE
> 
> #debug(spark_connect)
> 
> sc <- spark_connect(master = "sc://sparkhost", config = conf,method = "spark_connect",version = "3.5.0" )

! Your 'RETICULATE_PYTHON' environment variable was unset.
  To recover, restart R after you closing your Spark session
! No viable Python Environment was identified for Spark Connect version 3.5.0
  Do you wish to install Spark Connect version 3.5.0?

1: Yes
2: No
3: Cancel

Selection: 3


Thanks,
Elango

**Comment by elango-v** [comment]
FYI.... I upgraded python version to 3.11 but still facing the same above error

**Comment by elango-v** [comment]
Hi @edgararuiz , 

I installed pyspark already in my python & spark environment. How can I reuse that pyspark instead of installing again in R env (pysparklyr::install_pyspark("3.5", python_version = "3.10"))

Can you please confirm?

Thanks,
Elango
